var blogPosts = [{title: "<br><h3>Week 1</h3>", copy: "<p>My first week at Nashville Software School was a complete whirlwind. Even though I had been anticipating the start of NSS's six-month bootcamp for months, I learned quickly that I wouldn't know what I was in for until I arrived.</p>"
	            + "<p>The biggest challenge so far? Retraining my brain. Working consistently for hours at a time to learn and apply new concepts is not something my brain has actively been engaged in for quite some time. As a lifelong lover of learning, I came into this program believing I had an edge; I have always thrived in a classroom environment and love the energy that comes from a group of people working through projects/ideas/problems together. Having been mostly self-employed for the past several years, and before that having worked in positions that did not require much active problem-solving, I realized this week that that part of my brain has been turned off, perhaps for years.</p>"
	            + "<p>Retraining my brain to absorb highly technical concepts, then apply those concepts in a concrete way, is a task that has been harder than I anticipated. Even as I'm writing this, I'm noticing that my writing skills have taken quite a hit this past week... is my right brain slowly deactivating to make room for a more activated left brain? Or am I just exhausted? (I imagine both.)</p>"
	            + "<p> One of my major accomplishments this week? I think I finally understand Git and GitHub. Is that possible?</p>", date: "<h4>April 7, 2017</h4>" + "<br>"},
{title: "<h3>Week 2</h3>", copy: "<p>During my second week, I became more confident in some areas while flailing in others.</p>" + "<p>Despite my confidence about Git and GitHub, this came tumbling down when attempting to work through the Git workflow on a team. By the second group project, my confidence had returned, and I can say now that yes, I really do understand Git and GitHub!</p>"
	            + "<p>Feeling confident with my knowledge of Javascript  is another story.</p>", date: "<h4>April 14, 2017</h4>" + "<br>"}];

for (var i = 0; i < blogPosts.length; i++) {
	var blogPostsString = "<div class = 'thoughts" + (i + 1) + "'><h2>" + blogPosts[i].title + "</h2<p>" + blogPosts[i].copy + "</p>" + "<p>" + blogPosts[i].date + "</p></div>";
	document.getElementById("week1").innerHTML += blogPostsString
}
